feat: allow toggling the inlay-hint mode
chrisgrieser/nvim-lsp-endhints pull request #7
Opened 2024-08-17 22:20 UTC by vxpm

as discussed in #6

## Checklist
- [ ] Used only camelCase variable names.
- [ ] If functionality is added or modified, also made respective changes to the
  `README.md` (the `.txt` file is auto-generated and does not need to be modified).

2024-08-17 23:14 UTC, chrisgrieser requested changes
Minor stuff, but looks otherwise fine to me. 

If you add this new feature to the docs, we can merge this.

2024-08-17 23:14 UTC, chrisgrieser commented on lua/lsp-endhints/auto-enable.lua
> +	vim.lsp.inlay_hint.enable(true)
Why this addition?

2024-08-17 23:14 UTC, chrisgrieser commented on lua/lsp-endhints/override-handler.lua
>  	local originalDisableHandler = vim.lsp.inlay_hint.enable
Think this part needs to be removed now, as it is an up value now

2024-08-17 23:38 UTC, vxpm commented on lua/lsp-endhints/auto-enable.lua
> +	vim.lsp.inlay_hint.enable(true)
without it, `vim.lsp.inlay_hint.is_enabled` would be out of sync with the plugin, returning `false` even though inlay hints are showing

2024-08-17 23:38 UTC, vxpm commented on lua/lsp-endhints/override-handler.lua
>  	local originalDisableHandler = vim.lsp.inlay_hint.enable
i'm not sure i understand what you mean, could you elaborate?

2024-08-17 23:39 UTC, vxpm commented
cool! after the minor stuff is solved i'll add some docs then.

2024-08-17 23:40 UTC, chrisgrieser commented on lua/lsp-endhints/override-handler.lua
>  	local originalDisableHandler = vim.lsp.inlay_hint.enable
The original disable handle is what series by you at the top of the file outside the function, so there is no need to store it here anymore

2024-08-17 23:42 UTC, chrisgrieser commented on lua/lsp-endhints/auto-enable.lua
> +	vim.lsp.inlay_hint.enable(true)
Oh I see, though, is that related to the new feature or a bug that you fixed independently from the new feature?

2024-08-18 00:46 UTC, vxpm commented on lua/lsp-endhints/auto-enable.lua
> +	vim.lsp.inlay_hint.enable(true)
actually, after studying the code a little more i see that this was a misunderstanding of mine - it returned `false` because `autostart` only enables inlay hints for specific buffers, not globally. the new changes treat this correctly.

2024-08-18 00:46 UTC, vxpm commented on lua/lsp-endhints/override-handler.lua
>  	local originalDisableHandler = vim.lsp.inlay_hint.enable
done!

2024-08-18 05:53 UTC, chrisgrieser commented
Looks good know, remove the draft status when you the PR is ready 👍

2024-08-18 21:48 UTC, vxpm commented
think it's good to go

2024-08-18 22:04 UTC, merged

2024-08-18 22:35 UTC, chrisgrieser commented
Merged. Thanks for the PR!